### PR TITLE
Adding image and related markdown file

### PR DESCRIPTION
**Pull request by Wittionary**
## Contributor Checklist

Hi Friend! Thanks for contributing an open source art. Please make sure
you check off all the items below!

- [x] You've added your image as `docs/assets/<year>/<image>.jpg`
- [x] The image is not greater than 1024px in size (smaller runs faster!)
- [x] Your metadata post is added with the same `<image>` identifier in `docs/_works/<year>/<image>.md`
- [x] You have all fields in your metadata file described in [the README](https://github.com/vsoch/opensource-art#template)

Thanks for contributing, the robots can't wait to start working!

### How does this work?

When you create the pull request, it will start a workflow (that will appear below)
on a testing server called "CircleCI" that is going to use a [docker container](https://github.com/vsoch/deepdream-docker)
to generate an artistic piece (well, many!) for the gallery. There are a few steps here:

 - **build** will generate the art pieces, and save them as artifacts for us the preview! You can look at the link for the build step in the workflow and click on "Artifacts" to see them.
 - **update_cache** just saves things for next time.
 - **hold** is a step that requires a manual approval, meaning an administrator of the gallery checks the artifacts, and then gives the good to go!
 - **deploy** sends the images off to the gallery, where they can be appreciated by all.

Feel free to ask questions in the comments below, and let us know if anything is unclear. Thank
you again for your contribution!

### CODE REVIEW

**Comment by Wittionary** [comment]
Addresses issue #29

**Comment by vsoch** [comment]
Awesome! It found your work and deepdream is running now, I'll keep checking to see when it's updated and ready for checking of artifacts.

```
Previewing Works Metadata
2018/witt-allen-github-pic.jpg
0. Installing dependencies...
DeepDreams are made of cheese, who am I to diss a brie?
1. Preparing robot art studio!
Working directory is /tmp/src
2. Identifying new works!
2018/witt-allen-github-pic.jpg
3. Starting opensource-art container
```

**Comment by vsoch** [comment]
hey @Wittionary ! One small issue - the markdown needs to be named coinciding with the image. So it would need to be under `docs/_works/2018` as `witt-allen-github-pic.md`. Would you be able to update the file name and try the build again? Thank you!

**Comment by Wittionary** [comment]
@vsoch Hey, I tried rebasing it from CLI, but the Github GUI didn't say there was anything to commit so I'm kinda confused. I'm no git guru, but I did read most of the doc on _git rebase_ so I get the premise. Do you know what I'm doing wrong?

```bash
Witt@MONOLITH ~/My Documents/Github/wittionary/opensource-art (master)
$ git checkout wittionary-contribution
Switched to branch 'wittionary-contribution'
Your branch is up-to-date with 'origin/wittionary-contribution'.

Witt@MONOLITH ~/My Documents/Github/wittionary/opensource-art (wittionary-contribution)
$ git rebase master
Current branch wittionary-contribution is up to date.
```

**Comment by vsoch** [comment]
You need to add the repo here vsoch/opensource-art as a remote, then you need to pull from master of (whatever you named that remote). I usually do "upstream". If you show me your .git/config I can tell you what to have there, e.g.,

```
cat .git/config
```

**Comment by vsoch** [comment]
The typical git flow is that your master is in sync with my master, so you would want to:

 1. add the vsoch/opensource-art as remote "upstream"
 2. checkout your master and pull from upstream master
 3. push to your remote master
 4. checkout the branch for the PR
 5. then either pull from your master (or what I usually do is just pull from the upstream master)

**Comment by Wittionary** [comment]
Hmm. My local repo seems up-to-date with your master so it seems there's nothing to commit. Do I close this PR and do a new one?

For posterity, here are the commands I used:
```bash
Witt@Monolith MINGW64 ~/Documents/GitHub/wittionary/opensource-art (wittionary-contribution)
$ git status
On branch wittionary-contribution
Your branch is up to date with 'origin/wittionary-contribution'.

nothing to commit, working tree clean

Witt@Monolith MINGW64 ~/Documents/GitHub/wittionary/opensource-art (wittionary-contribution)
$ git remote add upstream https://github.com/vsoch/opensource-art.git
fatal: remote upstream already exists.

Witt@Monolith MINGW64 ~/Documents/GitHub/wittionary/opensource-art (wittionary-contribution)
$ git pull
Already up to date.

Witt@Monolith MINGW64 ~/Documents/GitHub/wittionary/opensource-art (wittionary-contribution)
$ cat .git/config
[core]
        repositoryformatversion = 0
        filemode = false
        bare = false
        logallrefupdates = true
        symlinks = false
        ignorecase = true
[submodule]
        active = .
[remote "origin"]
        url = https://github.com/Wittionary/opensource-art.git
        fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
        remote = origin
        merge = refs/heads/master
[remote "upstream"]
        url = https://github.com/vsoch/opensource-art.git
        fetch = +refs/heads/*:refs/remotes/upstream/*
[branch "wittionary-contribution"]
        remote = origin
        merge = refs/heads/wittionary-contribution
[branch "wittionary-grammar"]
        remote = origin
        merge = refs/heads/wittionary-grammar

Witt@Monolith MINGW64 ~/Documents/GitHub/wittionary/opensource-art (wittionary-contribution)
$ git pull upstream
You asked to pull from the remote 'upstream', but did not specify
a branch. Because this is not the default configured remote
for your current branch, you must specify a branch on the command line.

Witt@Monolith MINGW64 ~/Documents/GitHub/wittionary/opensource-art (wittionary-contribution)
$ git pull upstream master
From https://github.com/vsoch/opensource-art
 * branch            master     -> FETCH_HEAD
Merge made by the 'recursive' strategy.
 .circleci/config.yml                               |  21 +++------------------
 .gitignore                                         |   1 +
 README.md                                          |   2 +-
 .../2018/anurag-kumar-kaleidoscopic-galaxy.md      |   9 +++++++++
 docs/_works/2018/dan-monego-tinfoil.md             |  10 ++++++++++
 docs/_works/2018/kevin-lu-sunset.md                |   9 +++++++++
 docs/_works/2018/ljoonal-stare.md                  |  12 ++++++++++++
 .../2018/anurag-kumar-kaleidoscopic-galaxy.jpg     | Bin 0 -> 450076 bytes
 docs/assets/images/2018/dan-monego-tinfoil.jpg     | Bin 0 -> 274246 bytes
 docs/assets/images/2018/kevin-lu-sunset.jpg        | Bin 0 -> 138838 bytes
 docs/assets/images/2018/ljoonal-stare.jpg          | Bin 0 -> 105273 bytes
 11 files changed, 45 insertions(+), 19 deletions(-)
 create mode 100644 docs/_works/2018/anurag-kumar-kaleidoscopic-galaxy.md
 create mode 100644 docs/_works/2018/dan-monego-tinfoil.md
 create mode 100644 docs/_works/2018/kevin-lu-sunset.md
 create mode 100644 docs/_works/2018/ljoonal-stare.md
 create mode 100644 docs/assets/images/2018/anurag-kumar-kaleidoscopic-galaxy.jpg
 create mode 100644 docs/assets/images/2018/dan-monego-tinfoil.jpg
 create mode 100644 docs/assets/images/2018/kevin-lu-sunset.jpg
 create mode 100644 docs/assets/images/2018/ljoonal-stare.jpg

Witt@Monolith MINGW64 ~/Documents/GitHub/wittionary/opensource-art (wittionary-contribution)
$ git checkout master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.

Witt@Monolith MINGW64 ~/Documents/GitHub/wittionary/opensource-art (master)
$ git pull upstream master
From https://github.com/vsoch/opensource-art
 * branch            master     -> FETCH_HEAD
Updating 58e6899..9ef78dd
Fast-forward
 .circleci/config.yml                               |  21 +++------------------
 .gitignore                                         |   1 +
 README.md                                          |   2 +-
 .../2018/anurag-kumar-kaleidoscopic-galaxy.md      |   9 +++++++++
 docs/_works/2018/dan-monego-tinfoil.md             |  10 ++++++++++
 docs/_works/2018/kevin-lu-sunset.md                |   9 +++++++++
 docs/_works/2018/ljoonal-stare.md                  |  12 ++++++++++++
 .../2018/anurag-kumar-kaleidoscopic-galaxy.jpg     | Bin 0 -> 450076 bytes
 docs/assets/images/2018/dan-monego-tinfoil.jpg     | Bin 0 -> 274246 bytes
 docs/assets/images/2018/kevin-lu-sunset.jpg        | Bin 0 -> 138838 bytes
 docs/assets/images/2018/ljoonal-stare.jpg          | Bin 0 -> 105273 bytes
 11 files changed, 45 insertions(+), 19 deletions(-)
 create mode 100644 docs/_works/2018/anurag-kumar-kaleidoscopic-galaxy.md
 create mode 100644 docs/_works/2018/dan-monego-tinfoil.md
 create mode 100644 docs/_works/2018/kevin-lu-sunset.md
 create mode 100644 docs/_works/2018/ljoonal-stare.md
 create mode 100644 docs/assets/images/2018/anurag-kumar-kaleidoscopic-galaxy.jpg
 create mode 100644 docs/assets/images/2018/dan-monego-tinfoil.jpg
 create mode 100644 docs/assets/images/2018/kevin-lu-sunset.jpg
 create mode 100644 docs/assets/images/2018/ljoonal-stare.jpg

Witt@Monolith MINGW64 ~/Documents/GitHub/wittionary/opensource-art (master)
$ git push master
fatal: 'master' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Witt@Monolith MINGW64 ~/Documents/GitHub/wittionary/opensource-art (master)
$ cat .git/config
[core]
        repositoryformatversion = 0
        filemode = false
        bare = false
        logallrefupdates = true
        symlinks = false
        ignorecase = true
[submodule]
        active = .
[remote "origin"]
        url = https://github.com/Wittionary/opensource-art.git
        fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
        remote = origin
        merge = refs/heads/master
[remote "upstream"]
        url = https://github.com/vsoch/opensource-art.git
        fetch = +refs/heads/*:refs/remotes/upstream/*
[branch "wittionary-contribution"]
        remote = origin
        merge = refs/heads/wittionary-contribution
[branch "wittionary-grammar"]
        remote = origin
        merge = refs/heads/wittionary-grammar

Witt@Monolith MINGW64 ~/Documents/GitHub/wittionary/opensource-art (master)
$ git push origin master
  Enumerating objects: 100, done.
Counting objects: 100% (100/100), done.
Delta compression using up to 4 threads
Compressing objects: 100% (74/74), done.
Writing objects: 100% (89/89), 15.04 MiB | 1.23 MiB/s, done.
Total 89 (delta 45), reused 0 (delta 0)
remote: Resolving deltas: 100% (45/45), completed with 6 local objects.
To https://github.com/Wittionary/opensource-art.git
   58e6899..9ef78dd  master -> master

Witt@Monolith MINGW64 ~/Documents/GitHub/wittionary/opensource-art (master)
$   git checkout wittionary-contribution
Switched to branch 'wittionary-contribution'
Your branch is ahead of 'origin/wittionary-contribution' by 19 commits.
  (use "git push" to publish your local commits)

Witt@Monolith MINGW64 ~/Documents/GitHub/wittionary/opensource-art (wittionary-contribution)
$ git pull upstream master
From https://github.com/vsoch/opensource-art
 * branch            master     -> FETCH_HEAD
Already up to date.

Witt@Monolith MINGW64 ~/Documents/GitHub/wittionary/opensource-art (wittionary-contribution)
$ git status
On branch wittionary-contribution
Your branch is ahead of 'origin/wittionary-contribution' by 19 commits.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean

Witt@Monolith MINGW64 ~/Documents/GitHub/wittionary/opensource-art (wittionary-contribution)
$ git rebase master
First, rewinding head to replay your work on top of it...
Applying: Adding image and related markdown file
Applying: Changed filename

Witt@Monolith MINGW64 ~/Documents/GitHub/wittionary/opensource-art (wittionary-contribution)
$ git status
On branch wittionary-contribution
Your branch and 'origin/wittionary-contribution' have diverged,
and have 20 and 2 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

nothing to commit, working tree clean
```

**Comment by vsoch** [comment]
holy cow, yeah I think at this point you should start with a fresh clone. To be clear, you don't need to do all that work with your master. You can fork the repo here, pull, checkout a new branch, add the files, and push to your branch. The entire set of steps shouldn't need to go beyond:

```
git clone git@github.com:Wittionary/opensource-art
git checkout -b mycontribution
git add ...(files you want to add)
git commit -a -m "the message for my commit"
git push origin mycontribution
```

Then do a PR. Then for the current rebase that you needed to do, let's say we are on branch "mycontribution"

```
git remote add upstream https://github.com/vsoch/opensource-art.git
git pull upstream master
git push origin mycontribution
```

That's it :)

So I would back up the files, delete the entire repository (local and in your Github account) and start afresh. It will be easier this way than trying to cherry pick / debug what you did above - I'm having trouble following it to be honest. Don't give up! :)

**Comment by Wittionary** [comment]
Haha, thanks so much for your help! New PR is #41

**Pull request closed without merging**
