### PR TITLE
Adding the first image in 2019!

### PR DESCRIPTION
**Pull request by KevinLu**
## Contributor Checklist

Hi Friend! Thanks for contributing an open source art. Please make sure
you check off all the items below!

- [x] You've added your image as `docs/assets/<year>/<image>.jpg`
- [x] The image is not greater than 1024px in size (smaller runs faster!)
- [x] Your metadata post is added with the same `<image>` identifier in `docs/_works/<year>/<image>.md`
- [x] You have all fields in your metadata file described in [the README](https://github.com/vsoch/opensource-art#template)

Thanks for contributing, the robots can't wait to start working!

### How does this work?

When you create the pull request, it will start a workflow (that will appear below)
on a testing server called "CircleCI" that is going to use a [docker container](https://github.com/vsoch/deepdream-docker)
to generate an artistic piece (well, many!) for the gallery. There are a few steps here:

 - **build** will generate the art pieces, and save them as artifacts for us the preview! You can look at the link for the build step in the workflow and click on "Artifacts" to see them.
 - **update_cache** just saves things for next time.
 - **hold** is a step that requires a manual approval, meaning an administrator of the gallery checks the artifacts, and then gives the good to go!
 - **deploy** sends the images off to the gallery, where they can be appreciated by all.

Feel free to ask questions in the comments below, and let us know if anything is unclear. Thank
you again for your contribution!

### CODE REVIEW

**Comment by vsoch** [comment]
Awesome! I'll need to update the circle config (there have been some changes) but I'll wait for this preview to build first.

**Comment by vsoch** [comment]
okey doke! It's been a long time, but (I think) everything is good to deploy - the config is set to ignore master, so I think the update is done here. I'm going to remove the hold and let's hope everything works out ok :)

**Comment by vsoch** [comment]
It's reporting the envar isn't set (and I set it during the first build) so i triggered a rebuild, hoping now that it's detected.

**Comment by vsoch** [comment]
hey @KevinLu unfortunately it's not picking up GITHUB_EMAIL (which is likely a security thing so you can't re-run old workflows with new envars) so you'll need to do a trivial commit to trigger it again. Sorry about that!

**Comment by KevinLu** [comment]
Trivial commit done :D

**Comment by vsoch** [comment]
hey @KevinLu I don't want to leave you hanging - the config isn't finding an environment variable that's set, so 2 days ago I actually opened up a support ticket to Circle. I think we should hear back before the end of 2019, but of course it's not imminent! Sorry for the delay, the artifacts in the preview look really good!

**Comment by KevinLu** [comment]
@vsoch thanks for the update! that's fine for me, if the issue gets resolved let me know :)

**Comment by vsoch** [comment]
Will do! Sorry for the hiccup.

**Comment by vsoch** [comment]
okay I fixed it! I squashed and merged so the PR won't pick up on it here (and we can close) but your art is generated and added! https://vsoch.github.io/opensource-art/ Thanks for the contribution!

**Pull request closed without merging**
