### PR TITLE
Adding a vibrant image to the gallery

### PR DESCRIPTION
**Pull request by KevinLu**
## Contributor Checklist

Hi Friend! Thanks for contributing an open source art. Please make sure
you check off all the items below!

- [x] You've added your image as `docs/assets/<year>/<image>.jpg`
- [x] The image is not greater than 1024px in size (smaller runs faster!)
- [x] Your metadata post is added with the same `<image>` identifier in `docs/_works/<year>/<image>.md`
- [x] You have all fields in your metadata file described in [the README](https://github.com/vsoch/opensource-art#template)

Thanks for contributing, the robots can't wait to start working!

### How does this work?

When you create the pull request, it will start a workflow (that will appear below)
on a testing server called "CircleCI" that is going to use a [docker container](https://github.com/vsoch/deepdream-docker)
to generate an artistic piece (well, many!) for the gallery. There are a few steps here:

 - **build** will generate the art pieces, and save them as artifacts for us the preview! You can look at the link for the build step in the workflow and click on "Artifacts" to see them.
 - **update_cache** just saves things for next time.
 - **hold** is a step that requires a manual approval, meaning an administrator of the gallery checks the artifacts, and then gives the good to go!
 - **deploy** sends the images off to the gallery, where they can be appreciated by all.

Feel free to ask questions in the comments below, and let us know if anything is unclear. Thank
you again for your contribution!

### CODE REVIEW

**Comment by vsoch** [comment]
Woohoo! I can't wait to see this one :) It looks like Circle is having trouble allocating the container (this happened a few days ago) so I'll give it a little more time, and restart if it continues to bloop out. We will get it building soon! You chose a beautiful image, I can't wait to see it :city_sunset:

**Comment by vsoch** [comment]
Heyo! We are building!

A tiny issue I think - the file you called `docs/_works/2018/kevin-lu-sunset` should be a markdown file so it is found and rendered by the template. Could you please rename it to `docs/_works/2018/kevin-lu-sunset.md` ? Thank you!

**Comment by KevinLu** [comment]
Whoops! Can't believe I forgot to add the extension while saving the file. It's fixed now :)

**Comment by vsoch** [comment]
No worries! It found you now :)

```bash
Previewing Works Metadata
2018/kevin-lu-sunset.jpg
0. Installing dependencies...
DeepDreams are made of cheese, who am I to diss a brie?
1. Preparing robot art studio!
Working directory is /tmp/src
2. Identifying new works!
2018/kevin-lu-sunset.jpg
3. Starting opensource-art container
cfc7eebd3a86a2d15ca1d86b03567dc907ea0b440575a7864265428e643d4356
 === 2018/kevin-lu-sunset.jpg === 
kevin-lu-sunset.jpg
```
The deepdream container is running as we speak! I'll try to link some of the artifacts here after it finishes, or update you with any additional changes that are needed.

**Comment by vsoch** [comment]
Done! For your viewing and approval: 

This is the main "dreamy" image (the final of the sequence)
image

Frame 1
image

Frame 2
https://153-144051522-gh.circle-artifacts.com/0/opensource-art/outputs/frame-0001-kevin-lu-sunset.jpg

Frame 3
https://153-144051522-gh.circle-artifacts.com/0/opensource-art/outputs/frame-0002-kevin-lu-sunset.jpg

And the guided - which basically combines your contribution with a previous one to produce something entirely different.
image

**Comment by vsoch** [comment]
lol oups

**Comment by vsoch** [comment]
There we go! That's what I meant to do... accidentally hit the close and comment button :)

**Comment by KevinLu** [comment]
Looks beautiful! I love the arches on the wall!

**Comment by vsoch** [comment]
Me too :) I just approved the hold, so after a quick deploy step we should see the site live - I'll link it when it's there!

**Comment by vsoch** [comment]
hmm that's strange, it didn't detect the environment variables for the deploy- don't worry I'll look into this and fix up for you.

**Comment by vsoch** [comment]
Okay you are there now!

https://vsoch.github.io/opensource-art/works/kevin-lu-sunset/
And we've found a bug I need to look into - given coming from another fork, the secrets (checkout keys and GIthub account name stuffs) aren't passed forward. I had done the hold and then deploy (from the PR) so we wouldn't have to wait for the re-generation of the image again on master, so either I'll need to:

 1. have the merge --> then rebuild and deploy from master OR
 2. have the images and finished stuffs cached somewhere (that can be found on merge).

I'll think more about this, thank you for your contribution! Bootiful!

**Pull request merged**
